%% Plotter Function
% * Generates a heatmap from the heatmap matrix generated by periodfinder.
% Saves it as png.

function plotHeatMap = myheatmap(heatMapFolder, heatmapfile, heatmapimageFile)

if ~exist(heatMapFolder, 'dir')
    mkdir(heatMapFolder)
end           

set(0,'DefaultFigureVisible','on');
S = load(heatmapfile);
data = S.result;
x = S.alpha;
y = S.delay;
figure();
h = heatmap(y,x,data);
h.XLabel = "t_{shift}";
h.YLabel = "α";
colormap(flipud(jet))
colorbar
saveas(gcf, fullfile(heatMapFolder, heatmapimageFile));
plotHeatMap = true;

