%% Plotter Func
% This function plots all the signals generated by generateNice.

%%% Input:
% * The parameters and the heatmap file of signals.

%%% Output:
% * Plots of all signals generateNice simulates.

%%% Parameters:
% * heatmap:        alpha x delay matrix - heatmapFile of symbol durations that periodFinder
% generates
% * alpha:          integer or array     - M*(1-alpha) = IPTG, M*alpha = aTc
% * delay:          integer or array     - # of seconds between emissions of IPTG and aTc
% * M:              integer              - total # of molecules


function nicePlotter = nicePlotter(heatmapFile,alpha,delay,M,maxPeriod,bitSeqStr,plotFolder,imageFolder)
S = load(heatmapFile);
delayMat = S.result;
i1 = 0;
j1 = 0;
for a= alpha
    j1 = j1 + 1;
    i1 = 0;
    for d = delay
        i1 = i1 + 1;
        intDelay = round(delayMat(j1,i1));
        if(intDelay<maxPeriod)
            %%%
                % * the bit sequence below (4th argument of plotter
                % function) must be same with the generateNice sequence.
            plotter(M*(1-a),M*a,intDelay,bitSeqStr,d,plotFolder,imageFolder);
        end
    end
end